# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from f450_vision/box.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class box(genpy.Message):
  _md5sum = "f1a4a641427c15bc39cb4de0679f2e54"
  _type = "f450_vision/box"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 box_center_X
float32 box_center_Y
float32 box_center_W
float32 box_center_H
"""
  __slots__ = ['box_center_X','box_center_Y','box_center_W','box_center_H']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       box_center_X,box_center_Y,box_center_W,box_center_H

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(box, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.box_center_X is None:
        self.box_center_X = 0.
      if self.box_center_Y is None:
        self.box_center_Y = 0.
      if self.box_center_W is None:
        self.box_center_W = 0.
      if self.box_center_H is None:
        self.box_center_H = 0.
    else:
      self.box_center_X = 0.
      self.box_center_Y = 0.
      self.box_center_W = 0.
      self.box_center_H = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.box_center_X, _x.box_center_Y, _x.box_center_W, _x.box_center_H))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.box_center_X, _x.box_center_Y, _x.box_center_W, _x.box_center_H,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.box_center_X, _x.box_center_Y, _x.box_center_W, _x.box_center_H))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.box_center_X, _x.box_center_Y, _x.box_center_W, _x.box_center_H,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
