// Generated by gencpp from file f450_control/flag.msg
// DO NOT EDIT!


#ifndef F450_CONTROL_MESSAGE_FLAG_H
#define F450_CONTROL_MESSAGE_FLAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f450_control
{
template <class ContainerAllocator>
struct flag_
{
  typedef flag_<ContainerAllocator> Type;

  flag_()
    : flag(0)  {
    }
  flag_(const ContainerAllocator& _alloc)
    : flag(0)  {
  (void)_alloc;
    }



   typedef int16_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::f450_control::flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f450_control::flag_<ContainerAllocator> const> ConstPtr;

}; // struct flag_

typedef ::f450_control::flag_<std::allocator<void> > flag;

typedef boost::shared_ptr< ::f450_control::flag > flagPtr;
typedef boost::shared_ptr< ::f450_control::flag const> flagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f450_control::flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f450_control::flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f450_control::flag_<ContainerAllocator1> & lhs, const ::f450_control::flag_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f450_control::flag_<ContainerAllocator1> & lhs, const ::f450_control::flag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f450_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f450_control::flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f450_control::flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f450_control::flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f450_control::flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f450_control::flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f450_control::flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f450_control::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "703f20323013a67a9ef8aed4c09680ee";
  }

  static const char* value(const ::f450_control::flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x703f20323013a67aULL;
  static const uint64_t static_value2 = 0x9ef8aed4c09680eeULL;
};

template<class ContainerAllocator>
struct DataType< ::f450_control::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f450_control/flag";
  }

  static const char* value(const ::f450_control::flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f450_control::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 flag\n"
;
  }

  static const char* value(const ::f450_control::flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f450_control::flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f450_control::flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f450_control::flag_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F450_CONTROL_MESSAGE_FLAG_H
